//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace probando
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILE
    {
        public int ID_PERFIL { get; set; }
        public string NOMBRE_PERFIL { get; set; }
    }
}
